version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./whackywheels
    container_name: spring_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./ww-frontend
    container_name: angular_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./ww-frontend:/app
      - /app/node_modules 
    command: npx ng serve --host 0.0.0.0

volumes:
  db_data:
